export const TYPES = {
  BUG: 'Inseto',
  DARK: 'Sombrio',
  DRAGON: 'Dragão',
  ELECTRIC: 'Elétrico',
  FAIRY: 'Fada',
  FIGHTING: 'Lutador',
  FIRE: 'Fogo',
  FLYING: 'Voador',
  GHOST: 'Fantasma',
  GRASS: 'Planta',
  GROUND: 'Terrestre',
  ICE: 'Gelo',
  NORMAL: 'Normal',
  POISON: 'Venenoso',
  PSYCHIC: 'Psíquico',
  ROCK: 'Pedra',
  STEEL: 'Aço',
  WATER: 'Água',
};
