export const THEME = {
  TYPES: {
    BUG: 'BUG',
    DARK: 'DARK',
    DRAGON: 'DRAGON',
    ELECTRIC: 'ELECTRIC',
    FAIRY: 'FAIRY',
    FIGHTING: 'FIGHTING',
    FIRE: 'FIRE',
    FLYING: 'FLYING',
    GHOST: 'GHOST',
    GRASS: 'GRASS',
    GROUND: 'GROUND',
    ICE: 'ICE',
    NORMAL: 'NORMAL',
    POISON: 'POISON',
    PSYCHIC: 'PSYCHIC',
    ROCK: 'ROCK',
    STEEL: 'STEEL',
    WATER: 'WATER',
  },

  COLORS: {
    BUG: '#91c12f',
    DARK: '#5a5465',
    DRAGON: '#0b6dc3',
    ELECTRIC: '#f4d23c',
    FAIRY: '#ec8fe6',
    FIGHTING: '#ce416b',
    FIRE: '#ff9d55',
    FLYING: '#89aae3',
    GHOST: '#5269ad',
    GRASS: '#63bc5a',
    GROUND: '#d97845',
    ICE: '#73cec0',
    NORMAL: '#919aa2',
    POISON: '#b567ce',
    PSYCHIC: '#fa7179',
    ROCK: '#c5b78c',
    STEEL: '#5a8ea2',
    WATER: '#5090d6',
  },

  BACKGROUND: {
    BUG: '#8BD674',
    DARK: '#6F6E78',
    DRAGON: '#7383B9',
    ELECTRIC: '#F2CB55',
    FAIRY: '#EBA8C3',
    FIGHTING: '#EB4971',
    FIRE: '#FFA756',
    FLYING: '#83A2E3',
    GHOST: '#8571BE',
    GRASS: '#8BBE8A',
    GROUND: '#F78551',
    ICE: '#91D8DF',
    NORMAL: '#B5B9C4',
    POISON: '#9F6E97',
    PSYCHIC: '#FF6568',
    ROCK: '#D4C294',
    STEEL: '#4C91B2',
    WATER: '#58ABF6',
  },

  ICONS: {
    BUG: '/src/assets/types_svg/bug.svg',
    DARK: '/src/assets/types_svg/dark.svg',
    DRAGON: '/src/assets/types_svg/dragon.svg',
    ELECTRIC: '/src/assets/types_svg/electric.svg',
    FAIRY: '/src/assets/types_svg/fairy.svg',
    FIGHTING: '/src/assets/types_svg/fighting.svg',
    FIRE: '/src/assets/types_svg/fire.svg',
    FLYING: '/src/assets/types_svg/flying.svg',
    GHOST: '/src/assets/types_svg/ghost.svg',
    GRASS: '/src/assets/types_svg/grass.svg',
    GROUND: '/src/assets/types_svg/ground.svg',
    ICE: '/src/assets/types_svg/ice.svg',
    NORMAL: '/src/assets/types_svg/normal.svg',
    POISON: '/src/assets/types_svg/poison.svg',
    PSYCHIC: '/src/assets/types_svg/psychic.svg',
    ROCK: '/src/assets/types_svg/rock.svg',
    STEEL: '/src/assets/types_svg/steel.svg',
    WATER: '/src/assets/types_svg/water.svg',
  },
};
